site_name: Altibase Documentation
site_url: https://soyoon-choi-mkdocs-trial.readthedocs-hosted.com/ko/7.3/

theme:
  name: material
  palette:
    primary: custom
    accent: teal
  language: ko
  favicon: img/favicon.ico
  logo: img/logo_w.png
  features:
    - content.code.copy
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.share

nav:
  - Home: index.md
  - Admin:
    - Getting Started Guide: Admin/Getting Started Guide/
    - Installation Guide: Admin/Installation Guide/
    - Administartor's Manual: Admin/Administrator's Manual/
    - Replication Manual: Admin/Replication Manual/ 
    - Data Type & Altibase Properties: Admin/General_Reference-1.Data Types & Altibase Properties/
    - The Data Dictionary: Admin/General_Reference-2.The Data Dictionary/
    - DB Link User's guide: Admin/DB Link User's Manual/
    - Performance Tuning Guide: Admin/Performance Tuning Guide/
    - SNMP Agent Guide: Admin/SNMP Agent Guide/
  - Developer: Developer/index.md
  - Tools: Tools/index.md
  - Version-dependent Tools: Version-dependent Tools/index.md

extra:
#  version:
#    alias: true
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Korean
      link: /ko/
      lang: ko

extra_css:
  - custom/style.css

#extra_javascript:
#  - 'https://code.jquery.com/jquery-3.6.1.min.js'

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "#"
      toc_depth: 4
  - pymdownx.blocks.html:
  - pymdownx.blocks.details:
  - pymdownx.blocks.tab:
  - pymdownx.caret:

