site_name: Altibase Documentation
theme:
  name: readthedocs
  highlightjs: true
#plugins:
#  - search
#  - mkdocstrings:
#      handlers:
#        # See: https://mkdocstrings.github.io/python/usage/
#        python:
#          options:
#            docstring_style: sphinx
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"
