site_name: Altibase Documentation

theme:
  #name: readthedocs
  name: material
  #highlightjs: true

extra_css:
  - custom/style.css

plugins:
  - search

markdown_extensions:
  - attr_list
  #- toc:
  #  toc_depth: 3
  - footnotes
  - markdown.extensions.footnotes:
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "#"
  - pymdownx.blocks.html:
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
      - caution
  - pymdownx.blocks.definition:
  - pymdownx.blocks.details:
  - pymdownx.blocks.tab:
  - pymdownx.caret:

